Update to v0.9.16.1
7even/endless-ships pull request #13
Opened 2022-11-06 19:53 UTC by rezecib

This was my first encounter with any Lisp language, so I'm sure my code there could be improved.

Additionally, while testing this I noticed the following gaps/issues that I wasn't Lisp-proficient enough to fix:
- Firelight missile bank stats don't work, because it's got a weird two-stage projectile and the following in `src/clj/endless-ships/outfits.clj` only traverses one stage:
```clojure
                      :weapon (-> weapon-attrs
                                  (get-in [0 1])
                                  ->map
                                  (assoc :submunition (get-in weapon-attrs [0 1 "submunition" 0 0])))
```
- Langrage Hyper-Heaver stats are messed up, although it's a complicated weapon so not sure it's worth fixing.
- A lot of secondary weapons show both the pod and the launcher, which is a bit confusing.

I also was hoping to do the following, but couldn't figure out how to do it:
- Label outfits by race (pass the data subdirectory along when collecting data files?)
- Label outfits by whether they can be purchased (may require inversion or re-processing with the outfitters output, currently only done on the frontend)

(this was split from https://github.com/7even/endless-ships/pull/12)

2022-11-06 22:55 UTC, rezecib commented
force-push fixed some accidental tabs, converted back to space to be consistent with the rest of the repository

2022-12-28 18:00 UTC, 7even requested changes
I'll look into Firelight missile bank and Langrage Hyper-Heaver, maybe there is some simple solution.

2022-12-28 18:00 UTC, 7even commented on src/clj/endless_ships/core.clj
>     "ka'het ships.txt" :ka'het
Seems like this can be removed since the file was [renamed](https://github.com/endless-sky/endless-sky/pull/6471).

2022-12-28 18:00 UTC, 7even commented on src/clj/endless_ships/core.clj
>     "drak.txt" :drak
I also don't see this file in the game data, this can also be removed.

2022-12-28 18:00 UTC, 7even commented on src/clj/endless_ships/outfits.clj
> +                      (not (contains? #{"Imaginary Weapon" "Timer Weapon" "Mouthparts?"} name)))))
I don't think `"Mouthparts?"` should be excluded - they are used in several ships from `indigenous` "race".

2023-01-09 22:53 UTC, merged